50,2         T/B LAT'S    ET EAST COAST BASIN new 
W             WEST LONG    ET EAST COAST BASIN new  
85,35         L/R LON'S    ET EAST COAST BASIN new
FQUS23 KWNO 000000
GFS BASED STORM TIDE  (IN TENTHS OF FT)    NOT VALID FOR TROPICAL STORMS
13
