#!/bin/sh

########################################
# Runs GFS MDL Extratropical Storm Surge Model
########################################

set -x
date
export PS4=' $SECONDS + '

#####################################
# SET SHELL PROCESSING VARIABLES
#####################################

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir $DATA
export SHPetss=$DATA/shp
export IMGetss=$DATA/img
mkdir $DATA/shp
mkdir $DATA/img

cd $DATA
export NET=${NET:-etss}
export RUN=${RUN:-etss}

export LOCALJLOG="YES"
export jlogfile="${DATA}/jlogfile.${jobid:?}"

export pgmout="OUTPUT.${pid}"
export cycle=${cycle:-t${cyc}z}

export EXECetss=$HOMEetss/exec
export PARMetss=${HOMEetss}/parm/drawshp
export USHetss=${HOMEetss}/ush
export SCRIetss=$HOMEetss/scripts

setpdy.sh
. ./PDY

export COMIN=${COMIN:-$(compath.py ${NET}/${etss_ver}/${RUN}.${PDY})}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${etss_ver}/${RUN}.${PDY})}

mkdir -p ${COMOUT}

########################################################
# Execute the script.
${SCRIetss}/exetss_drawimages.sh
export err=$?; err_chk
########################################################

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

if [[ "${LOCALJLOG}" == "YES" ]]; then
  if [[ ! -r "${jlogfile}" ]]; then
    echo "Cannot read jlogfile (${jlogfile})"
  elif [[ ! -s "${jlogfile}" ]]; then
    echo "Jlogfile (${jlogfile}) is 0 bytes."
  else
    cp "${jlogfile}" "${COMOUT}"
  fi
fi

cat $pgmout

if [ "${KEEPDATA}" != "YES" ]; then
  cd $DATAROOT
  rm -rf $DATA
fi

date

